[env:yolo_uno]
platform = espressif32
board = yolo_uno
framework = arduino
monitor_speed = 115200

; ==================== FIX LỖI CLOSE() + ADAFRUIT MQTT ====================
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 
; ======================================================================

lib_deps = 
    tanakamasayuki/TensorFlowLite_ESP32 @ 1.0.0
    adafruit/Adafruit NeoPixel @ ^1.15.1
    robtillaart/DHT20 @ ^0.3.1        
    knolleary/PubSubClient @ ^2.8
    ayushsharma82/ElegantOTA
    ;adafruit/Adafruit MQTT Library @ ^2.4.0
    marcoschwartz/LiquidCrystal_I2C@^1.1.4